### ISSUE TITLE
Support non ASCII characters in PDFs

### ISSUE THREAD

**Issue by maxammann** [ehrenamtskarte/ehrenamtskarte#359] opened 2021-05-02 13:57 UTC
**Describe the bug**
See #353 for reference. We should support äüöß and possibly all unicode charactesr

**Comment by Schedulaar** [comment] 2021-05-02 13:59
This is a duplicate of https://github.com/ehrenamtskarte/ehrenamtskarte/issues/354

**Closed by Schedulaar** 2021-05-02 13:59 UTC
Labels: bug
